# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import message2_pb2 as message2__pb2


class DecoderStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.decodeMessage = channel.unary_unary(
                '/encryptmessage.Decoder/decodeMessage',
                request_serializer=message2__pb2.decodeRequest.SerializeToString,
                response_deserializer=message2__pb2.decodeResponse.FromString,
                )
        self.encodeMessage = channel.unary_unary(
                '/encryptmessage.Decoder/encodeMessage',
                request_serializer=message2__pb2.encodeRequest.SerializeToString,
                response_deserializer=message2__pb2.encodeResponse.FromString,
                )


class DecoderServicer(object):
    """Missing associated documentation comment in .proto file."""

    def decodeMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def encodeMessage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DecoderServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'decodeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.decodeMessage,
                    request_deserializer=message2__pb2.decodeRequest.FromString,
                    response_serializer=message2__pb2.decodeResponse.SerializeToString,
            ),
            'encodeMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.encodeMessage,
                    request_deserializer=message2__pb2.encodeRequest.FromString,
                    response_serializer=message2__pb2.encodeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'encryptmessage.Decoder', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Decoder(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def decodeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/encryptmessage.Decoder/decodeMessage',
            message2__pb2.decodeRequest.SerializeToString,
            message2__pb2.decodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def encodeMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/encryptmessage.Decoder/encodeMessage',
            message2__pb2.encodeRequest.SerializeToString,
            message2__pb2.encodeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
